"""
LLM-as-a-Judge for company enrichment.

Evaluates whether the enrichment generated by the LLM is actually
supported by the website content.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from openai import OpenAI, APIError, APITimeoutError

from utils.logger import get_logger

logger = get_logger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_ROOT / ".env"

GROQ_BASE_URL = "https://api.groq.com/openai/v1"
DEFAULT_MODEL = "llama-3.3-70b-versatile"

MAX_WEBSITE_TEXT = 12000


class LLMJudgeError(Exception):
    """Raised when LLM Judge fails."""


def judge_enrichment(
    *,
    website_text: str,
    llm_output: dict[str, Any],
    excel_data: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """
    Judge whether LLM enrichment is supported by website content.

    Returns
    -------
    dict
        {
            judge_score,
            decision,
            hallucination,
            supported_fields,
            unsupported_fields,
            missing_information,
            reasoning
        }
    """

    if ENV_FILE.exists():
        load_dotenv(ENV_FILE)

    api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        raise LLMJudgeError("Missing GROQ_API_KEY")

    if len(website_text) > MAX_WEBSITE_TEXT:
        website_text = website_text[:MAX_WEBSITE_TEXT]

    client = OpenAI(
        api_key=api_key,
        base_url=GROQ_BASE_URL,
    )

    system_prompt = """
You are an expert AI evaluator.

Your job is NOT to generate enrichment.

Your job is to judge whether an AI-generated enrichment is supported by the website.

Rules:

- Never invent facts.
- Use ONLY website evidence.
- If website doesn't mention something,
  consider it missing instead of hallucinated.

Return ONLY valid JSON.
"""

    user_prompt = f"""
WEBSITE CONTENT

{website_text}


EXCEL DATA

{json.dumps(excel_data or {}, indent=2)}


LLM OUTPUT

{json.dumps(llm_output, indent=2)}


Evaluate the enrichment.

Return JSON exactly like this:

{{
    "judge_score":95,
    "decision":"PASS",
    "hallucination":false,
    "supported_fields":[
        "industry",
        "products"
    ],
    "unsupported_fields":[
        "pricing"
    ],
    "missing_information":[
        "CEO Name"
    ],
    "reasoning":"Short explanation."
}}
"""

    logger.info("Running LLM Judge...")

    try:

        response = client.chat.completions.create(

            model=DEFAULT_MODEL,

            temperature=0,

            response_format={"type": "json_object"},

            messages=[
                {
                    "role": "system",
                    "content": system_prompt,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                },
            ],
        )

    except APITimeoutError as exc:
        raise LLMJudgeError("Groq timeout") from exc

    except APIError as exc:
        raise LLMJudgeError(f"Groq API Error: {exc}") from exc

    except Exception as exc:
        raise LLMJudgeError(str(exc)) from exc

    content = response.choices[0].message.content

    if not content:
        raise LLMJudgeError("Empty response")

    try:

        result = json.loads(content)

    except Exception as exc:
        raise LLMJudgeError("Invalid JSON returned by Judge") from exc

    logger.info("LLM Judge completed")

    return result